# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaShopList', '0002_auto_20160409_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='chosen_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AlexaShopList.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AlexaShopList.Search'),
        ),
    ]
