# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaShopList', '0005_auto_20160409_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
