# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaShopList', '0006_offer_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AlexaShopList.Search'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shop_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shop_product_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shop_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_phrase',
            field=models.TextField(null=True),
        ),
    ]
